In [51]:
import numpy as np
import pandas as pd
import random

data_set=pd.read_csv("C:\\Users\\HP\\Desktop\\Git_AI_Work\\AI & Machine Learning Algorithms\\datasets\\Iris.csv")
data_set.head(150)

data_set=data_set.sample(frac=1)
data_set.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
100  101            6.3           3.3            6.0           2.5   
132  133            6.4           2.8            5.6           2.2   
143  144            6.8           3.2            5.9           2.3   
108  109            6.7           2.5            5.8           1.8   
49    50            5.0           3.3            1.4           0.2   

            Species  
100  Iris-virginica  
132  Iris-virginica  
143  Iris-virginica  
108  Iris-virginica  
49      Iris-setosa

In [52]:
features = data_set.values[:, 1:5]  #x
labels= data_set.values[: , 5]  # y

In [53]:
#75% training and 25% testing
test=0
train=input("enter training percentage: ")
# test=str(100-int(test))
#find 75% of 149 records


enter training percentage: 75


In [54]:
max_index=int(len(data_set)*int(train)/100)
# test1=len(data_set)-train1

feature_train=features[0:max_index,:]

feature_test=features[max_index:len(data_set),:]

label_train=labels[0:max_index]

label_test=labels[max_index:len(data_set)]

In [55]:
print(features)
print(labels)
print(feature_train)
print(feature_test)
print(label_train)
print(label_test)

[[6.3 3.3 6.0 2.5]
 [6.4 2.8 5.6 2.2]
 [6.8 3.2 5.9 2.3]
 [6.7 2.5 5.8 1.8]
 [5.0 3.3 1.4 0.2]
 [5.0 3.5 1.6 0.6]
 [5.7 3.8 1.7 0.3]
 [6.7 3.3 5.7 2.5]
 [6.9 3.1 5.4 2.1]
 [4.5 2.3 1.3 0.3]
 [7.2 3.2 6.0 1.8]
 [5.2 4.1 1.5 0.1]
 [6.2 2.8 4.8 1.8]
 [5.4 3.0 4.5 1.5]
 [4.8 3.4 1.9 0.2]
 [4.9 3.0 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [7.2 3.6 6.1 2.5]
 [6.4 3.2 5.3 2.3]
 [5.7 2.5 5.0 2.0]
 [6.3 2.9 5.6 1.8]
 [5.8 2.8 5.1 2.4]
 [6.2 2.2 4.5 1.5]
 [6.5 3.0 5.2 2.0]
 [4.9 2.4 3.3 1.0]
 [4.9 2.5 4.5 1.7]
 [5.3 3.7 1.5 0.2]
 [5.6 2.9 3.6 1.3]
 [6.2 3.4 5.4 2.3]
 [5.5 4.2 1.4 0.2]
 [6.4 2.7 5.3 1.9]
 [6.0 2.2 5.0 1.5]
 [5.8 4.0 1.2 0.2]
 [6.1 2.8 4.0 1.3]
 [6.1 3.0 4.6 1.4]
 [4.6 3.1 1.5 0.2]
 [6.3 2.3 4.4 1.3]
 [4.6 3.4 1.4 0.3]
 [6.7 3.0 5.0 1.7]
 [6.3 3.4 5.6 2.4]
 [5.4 3.4 1.7 0.2]
 [6.0 2.9 4.5 1.5]
 [4.4 2.9 1.4 0.2]
 [5.6 2.8 4.9 2.0]
 [6.8 3.0 5.5 2.1]
 [5.5 2.4 3.7 1.0]
 [6.0 3.0 4.8 1.8]
 [6.2 2.9 4.3 1.3]
 [6.1 3.0 4.9 1.8]
 [5.1 3.8 1.5 0.3]
 [5.5 2.4 3.8 1.1]
 [4.9 3.1 1.5 0.1]
 [7.7 2.8 6.

In [59]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier( alpha=(0.0001),hidden_layer_sizes=(100, ), random_state=1)

# clf=MLPClassifier( hidden_layer_sizes=(100, ), activation='relu', solver='adam', alpha=0.0001, 
#               batch_size='auto', learning_rate='constant', learning_rate_init=0.001, power_t=0.5, 
#               max_iter=200, shuffle=True, random_state=None, tol=0.0001, verbose=False, warm_start=False, 
#               momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.9, 
#               beta_2=0.999, epsilon=1e-08, n_iter_no_change=10)

clf.fit(feature_train, label_train)
# MLPClassifier(alpha=1e-05, hidden_layer_sizes=(1, 3), random_state=1,solver='lbfgs')

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=1, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [60]:
label_pred= clf.predict(feature_test)

In [61]:
count=0
for t,p in zip(label_test, label_pred):
    print(t+"->"+p)
    count=count+1
print("Total tsetings:",count)

count1=0
for t,p in zip(label_test, label_pred):
    if(t==p):
        count1=count1+1
    
print("correct pred:",count1)
acc=(count1/len(label_test))*100

print("Accuracy",acc)

Iris-virginica->Iris-virginica
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-versicolor
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-versicolor
Iris-virginica->Iris-virginica
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-versicolor
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-virginica
Iris-versicolor->Iris-versicolor
Iris-setosa->Iris-setosa
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-versicolor
Iris-setosa->Iris-setosa
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-versicolor
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-versicolor
Iris-setosa->Iris-setosa
Iris-virginica->Iris-virginica
Iris-virginica->Iris-virginica
Iris-versicolor->Iris-versicolor
Iris-versicolor->Iris-virginica
Iris-setosa->Iris-setosa
Iris-virginica->Iris-virginica
Iris-versicolor->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-virginica->Iris-virginica
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-virgini

In [73]:
import numpy as np
  
# class NeuralNet(object): 
#     def __init__(self): 
#         # Generate random numbers 
#         np.random.seed(1) 
  
#         # Assign random weights to a 3 x 1 matrix, 
#         self.synaptic_weights = 2 * np.random.random((3, 1)) - 1
  
#     # The Sigmoid function 
#     def __sigmoid(self, x): 
#         return 1 / (1 + np.exp(-x)) 
  
#     # The derivative of the Sigmoid function. 
#     # This is the gradient of the Sigmoid curve. 
#     def __sigmoid_derivative(self, x): 
#         return x * (1 - x) 
  
#     # Train the neural network and adjust the weights each time. 
#     def train(self, inputs, outputs, training_iterations): 
#         for iteration in range(training_iterations): 
  
#             # Pass the training set through the network. 
#             output = self.learn(inputs) 
  
#             # Calculate the error 
#             error = outputs - output 
  
#             # Adjust the weights by a factor 
#             factor = np.dot(inputs.T, error * self.__sigmoid_derivative(output)) 
#             self.synaptic_weights += factor 
  
#     # The neural network thinks. 
#     def learn(self, inputs): 
#         return self.__sigmoid(np.dot(inputs, self.synaptic_weights)) 


# #Initialize 
# neural_network = NeuralNet() 

# The training set. 
inputs = np.array([[0, 1, 1], [1, 0, 0], [1, 0, 1]]) 
outputs = np.array([[1, 0, 1]]).T 

# # Train the neural network 
# neural_network.train(inputs, outputs, 10000) 

# # Test the neural network with a test example. 
# print (neural_network.learn(np.array([1, 0, 1])))

from sklearn.neural_network import MLPClassifier

clf = MLPClassifier( alpha=(0.0001),hidden_layer_sizes=(100, ), random_state=1)

# clf=MLPClassifier( hidden_layer_sizes=(100, ), activation='relu', solver='adam', alpha=0.0001, 
#               batch_size='auto', learning_rate='constant', learning_rate_init=0.001, power_t=0.5, 
#               max_iter=200, shuffle=True, random_state=None, tol=0.0001, verbose=False, warm_start=False, 
#               momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.9, 
#               beta_2=0.999, epsilon=1e-08, n_iter_no_change=10)

clf.fit(inputs, outputs)
# MLPClassifier(alpha=1e-05, hidden_layer_sizes=(1, 3), random_state=1,solver='lbfgs')

clf.predict(inputs)

confidence=clf.score(inputs, outputs)
print("accuracy",confidence*100)

accuracy 100.0


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [8]:
import numpy as np

def sigmoid(x,derivative=False):
    if(derivative==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

np.random.seed(1)

weights = np.random.randn(1, 3)

training = np.array([[np.array([0, 0, 0]).reshape(1, -1), 1],
                    [np.array([0,0,1]).reshape(1, -1), 0],
                    [np.array([0,1,0]).reshape(1, -1), 0],
                    [np.array([0,1,1]).reshape(1, -1), 0],
                    [np.array([1, 0, 0]).reshape(1, -1), 1],
                    [np.array([1,0, 1]).reshape(1, -1), 0],
                    [np.array([1,1,0]).reshape(1, -1), 0],
                    [np.array([1,1,1]).reshape(1, -1), 1],
                    ])

for iter in range(training.shape[0]):
#forwardPropagation:
        a_layer1 = training[iter][0]
        z_layer2 = np.dot(weights,a_layer1.reshape(-1, 1))
        a_layer2 = sigmoid(z_layer2)
        hypothesis_theta = a_layer2

#backPropagation:
        delta_neuron1_layer2 =  (a_layer2 - training[iter][1] ) * sigmoid(a_layer2 , derivative=True)
        Delta_neuron1_layer2 = np.dot(delta_neuron1_layer2 , a_layer1)
        update = Delta_neuron1_layer2
        weights = weights - update 


x = np.array([0,0, 1])
if (sigmoid(np.dot(weights,x.reshape(-1, 1))) >= 0.5):
    print("Prediction:",1)
else:
    print("Prediction:",0)
    
x = np.array([0,1,1])
if (sigmoid(np.dot(weights,x.reshape(-1, 1))) >= 0.5):
    print("Prediction:",1)
else:
    print("Prediction:",0)
    
x = np.array([1,1,1])
if (sigmoid(np.dot(weights,x.reshape(-1, 1))) >= 0.5):
    print("Prediction:",1)
else:
    print("Prediction:",0)

Prediction: 0
Prediction: 0
Prediction: 1
