In [17]:
# Using GA, it is required to find the maximum of a function, f(x) = ((a + 2b + 3c + 4d) - 30) where a,b,c and d 
# are genes to form a chromosome. Write a program to implement and show the best individual, best fitness, 
# average fitness, and poorest fitness against the generation. For demonstration purposes, the following simple set 
# of parameters is to be used to design the algorithm.
# •	Number of generations: 30
# •	The  population size: 6
# •	The  crossover rate : 1.0
# •	The  mutation rate: 0.1 
# •	Number of bits in each chromosome: 4

import numpy as np

In [18]:
# step01 --> population initialization


# Generate an initial population P
popu = np.random.randint(10,size=(6,4))
print("Population\n",popu)

Population
 [[7 0 7 5]
 [6 0 1 6]
 [0 8 1 1]
 [5 7 6 3]
 [7 9 9 0]
 [2 5 8 9]]


In [19]:
#Step02  --> fitness calculation


def fitness(chromosome):
    return chromosome[0]+2*chromosome[1]+3*chromosome[2]+4*chromosome[3]

# pass each row of popu(numpy array) from fitness fuction to find the fitness of each row
fit=[]
for i in range(0,6):
    b=fitness(popu[i])
    fit.append(b)   
    
print("Fitness of each row\n",fit)

Fitness of each row
 [48, 33, 23, 49, 52, 72]


In [20]:
# •	Number of generations: 30
fits=[]
for i in range(0,6):
    d=abs(fit[i]-30)
    fits.append(d)
    
print(fits)

[18, 3, 7, 19, 22, 42]


In [21]:
#find 2 minimum index from fits array
# to select 2 random rows from popu array

min1=fits.index(min(fits))
print(min1)

fits[min1]=1000

min2=fits.index(min(fits))
print(min2)

p1=popu[min1]
p2=popu[min2]

print("parents 1:",p1)
print("parent 2:",p2)

1
2
parents 1: [6 0 1 6]
parent 2: [0 8 1 1]


In [22]:
# step03  --> crossover


def swap(x,y):
    lst1=[]
    for i in x:
        lst1.append(i)
    for i in y:
        lst1.append(i)
    return lst1

def crossover(p1,p2):
    
    mid = int(len(p1)/2)
    
    o1=swap(list(p1[0:mid]),list(p2[mid:len(p2)]))
    o2=swap(list(p2[0:mid]),list(p1[mid:len(p1)]))
    
    return o1,o2

o1,o2=crossover(p1,p2)

print("Offspring1: ",o1)
print("Offspring2: ",o2)

Offspring1:  [6, 0, 1, 1]
Offspring2:  [0, 8, 1, 6]


In [23]:
# step04 --> Mutation

def mutation(o1,o2):
    r_ind=np.random.randint(0,4)
    print("random index: ",r_ind) #random index where we apply mutation
    o1[r_ind]=o1[r_ind]+0.1
    o2[r_ind]=o2[r_ind]+0.1
    print(o1,o2)
    
mutation(o1,o2)   

random index:  3
[6, 0, 1, 1.1] [0, 8, 1, 6.1]
