In [28]:
# real life Example of Decision tree algorithm
# http://what-when-how.com/artificial-intelligence/decision-tree-applications-for-data-modelling-artificial-intelligence/
# https://medium.com/greyatom/decision-trees-a-simple-way-to-visualize-a-decision-dc506a403aeb
# loan approval
# 
# 
# https://www.youtube.com/watch?v=qDcl-FRnwSU
# https://www.youtube.com/watch?v=PHxYNGo8NcI

# scikit
# https://www.youtube.com/watch?v=0Lt9w-BxKFQ
# https://www.youtube.com/watch?v=bwZ3Qiuj3i8 -->this
# https://www.youtube.com/watch?v=RZYjsw6P4nI -->spam email


# spam detection
# stock price prediction
# wether prediction


import numpy as np
import pandas as pd
import random

# step01 --> select a data set for training and testing


data_set=pd.read_csv("C:\\Users\\HP\\Desktop\\Git_AI_Work\\AI & Machine Learning Algorithms\\Iris.csv")


data_set=data_set.sample(frac=1) # for rows shuffling

data_set.head(150)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
9     10            4.9           3.1            1.5           0.1   
126  127            6.2           2.8            4.8           1.8   
39    40            5.1           3.4            1.5           0.2   
102  103            7.1           3.0            5.9           2.1   
0      1            5.1           3.5            1.4           0.2   
144  145            6.7           3.3            5.7           2.5   
70    71            5.9           3.2            4.8           1.8   
149  150            5.9           3.0            5.1           1.8   
100  101            6.3           3.3            6.0           2.5   
22    23            4.6           3.6            1.0           0.2   
93    94            5.0           2.3            3.3           1.0   
32    33            5.2           4.1            1.5           0.1   
74    75            6.4           2.9            4.3           1.3   
115  116            6.4           3.2            5.3           2.3   
58    59            6.6           2.9            4.6           1.3   
124  125            6.7           3.3            5.7           2.1   
96    97            5.7           2.9            4.2           1.3   
29    30            4.7           3.2            1.6           0.2   
91    92            6.1           3.0            4.6           1.4   
12    13            4.8           3.0            1.4           0.1   
20    21            5.4           3.4            1.7           0.2   
75    76            6.6           3.0            4.4           1.4   
10    11            5.4           3.7            1.5           0.2   
46    47            5.1           3.8            1.6           0.2   
132  133            6.4           2.8            5.6           2.2   
122  123            7.7           2.8            6.7           2.0   
55    56            5.7           2.8            4.5           1.3   
98    99            5.1           2.5            3.0           1.1   
24    25            4.8           3.4            1.9           0.2   
61    62            5.9           3.0            4.2           1.5   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
43    44            5.0           3.5            1.6           0.6   
50    51            7.0           3.2            4.7           1.4   
106  107            4.9           2.5            4.5           1.7   
133  134            6.3           2.8            5.1           1.5   
25    26            5.0           3.0            1.6           0.2   
112  113            6.8           3.0            5.5           2.1   
108  109            6.7           2.5            5.8           1.8   
78    79            6.0           2.9            4.5           1.5   
118  119            7.7           2.6            6.9           2.3   
101  102            5.8           2.7            5.1           1.9   
40    41            5.0           3.5            1.3           0.3   
76    77            6.8           2.8            4.8           1.4   
42    43            4.4           3.2            1.3           0.2   
84    85            5.4           3.0            4.5           1.5   
148  149            6.2           3.4            5.4           2.3   
51    52            6.4           3.2            4.5           1.5   
129  130            7.2           3.0            5.8           1.6   
92    93            5.8           2.6            4.0           1.2   
66    67            5.6           3.0            4.5           1.5   
143  144            6.8           3.2            5.9           2.3   
48    49            5.3           3.7            1.5           0.2   
30    31            4.8           3.1            1.6           0.2   
73    74            6.1           2.8            4.7           1.2   
15    16            5.7           4.4            1.5           0.4   
113  114        

In [29]:
# step02 --> seperate features and labels from dataset

features = data_set.values[:, 1:5]  #x
labels= data_set.values[: , 5]  # y

In [30]:
# step03 --> take input of what percentage of data we want to train from dataset

train=input("Enter Training Percentage: ")



Enter Training Percentage: 75


In [31]:
# step04 -->  seperate data for training and testing purpose:

max_index=int(len(data_set)*int(train)/100) #find last index num for 75% training data

# seperate features and labels from Training dataset
feature_train=features[0:max_index,:]
label_train=labels[0:max_index]

# seperate features and labels from Testing dataset   *labels are useless in training dataset
feature_test=features[max_index:len(data_set),:]
label_test=labels[max_index:len(data_set)] # in the end we use label_test for checking the percentage of correct prediction


print(features)
print(labels)
print(feature_train)
print(feature_test)
print(label_train)
print(label_test)

[[4.9 3.1 1.5 0.1]
 [6.2 2.8 4.8 1.8]
 [5.1 3.4 1.5 0.2]
 [7.1 3.0 5.9 2.1]
 [5.1 3.5 1.4 0.2]
 [6.7 3.3 5.7 2.5]
 [5.9 3.2 4.8 1.8]
 [5.9 3.0 5.1 1.8]
 [6.3 3.3 6.0 2.5]
 [4.6 3.6 1.0 0.2]
 [5.0 2.3 3.3 1.0]
 [5.2 4.1 1.5 0.1]
 [6.4 2.9 4.3 1.3]
 [6.4 3.2 5.3 2.3]
 [6.6 2.9 4.6 1.3]
 [6.7 3.3 5.7 2.1]
 [5.7 2.9 4.2 1.3]
 [4.7 3.2 1.6 0.2]
 [6.1 3.0 4.6 1.4]
 [4.8 3.0 1.4 0.1]
 [5.4 3.4 1.7 0.2]
 [6.6 3.0 4.4 1.4]
 [5.4 3.7 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [6.4 2.8 5.6 2.2]
 [7.7 2.8 6.7 2.0]
 [5.7 2.8 4.5 1.3]
 [5.1 2.5 3.0 1.1]
 [4.8 3.4 1.9 0.2]
 [5.9 3.0 4.2 1.5]
 [6.1 3.0 4.9 1.8]
 [4.8 3.4 1.6 0.2]
 [6.9 3.1 5.4 2.1]
 [4.8 3.0 1.4 0.3]
 [5.1 3.3 1.7 0.5]
 [6.3 2.3 4.4 1.3]
 [5.6 2.5 3.9 1.1]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [5.0 3.6 1.4 0.2]
 [5.5 2.4 3.7 1.0]
 [6.7 3.0 5.0 1.7]
 [6.3 2.7 4.9 1.8]
 [5.4 3.4 1.5 0.4]
 [6.5 3.2 5.1 2.0]
 [4.4 3.0 1.3 0.2]
 [5.5 3.5 1.3 0.2]
 [7.2 3.6 6.1 2.5]
 [4.4 2.9 1.4 0.2]
 [6.5 3.0 5.5 1.8]
 [5.5 2.6 4.4 1.2]
 [5.6 2.7 4.2 1.3]
 [7.2 3.2 6.

In [32]:
# step05 -->   use sklearn library for training and testing of dataset

from sklearn.tree import  DecisionTreeClassifier  # very helpful library in machine learning

model= DecisionTreeClassifier()



In [33]:
# step06 -->   train the model


model.fit(feature_train, label_train) #training ke time pr label or features dono chahiye hote he

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [34]:
# step07 -->   test the model


# save predicted values of model
label_pred= model.predict(feature_test)

# check predicted values of model whether they are correct or not
total_values=0
correct_values=0
for t,p in zip(label_test, label_pred):
    print(t+"->"+p)
    
    total_values = total_values+1
    
    if(t==p):
        correct_values=correct_values+1



Iris-virginica->Iris-virginica
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-setosa->Iris-setosa
Iris-setosa->Iris-setosa
Iris-setosa->Iris-setosa
Iris-virginica->Iris-virginica
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-versicolor
Iris-virginica->Iris-versicolor
Iris-virginica->Iris-virginica
Iris-setosa->Iris-setosa
Iris-virginica->Iris-virginica
Iris-virginica->Iris-virginica
Iris-versicolor->Iris-versicolor
Iris-virginica->Iris-virginica
Iris-virginica->Iris-virginica
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-versicolor
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-versicolor
Iris-virginica->Iris-virginica
Iris-versicolor->Iris-versicolor
Iris-virginica->Iris-virginica
Iris-versicolor->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-virginica->Iris-virginica
Iris-setosa->Iris-setosa
Iris-setosa->Iris-setosa
Iris-versicolor->Iris-versicolor
Iris-setosa->Iris-setosa
Iris-virginica->Iris

In [35]:
# step08 -->   find the percetange of prediction 

print("Total number of testing values: ",total_values)
print("Total number of testing values which are correct: ",correct_values)

acc=(correct_values/len(label_test))*100
print("Percentage of correct prediction by Model: ",acc)

Total number of testing values:  38
Total number of testing values which are correct:  37
Percentage of correct prediction by Model:  97.36842105263158


In [37]:
# step09 -->   test the model by user input 

sepal_len=float(input("Enter sepal_len(cm):"))
sepal_width=float(input("Enter sepal_width(cm):"))
petal_len=float(input("Enter petal_len(cm):"))
petal_width=float(input("Enter petal_width(cm):"))

x=np.array([sepal_len,sepal_width,petal_len,petal_width])

new_label= model.predict(x.reshape(1,-1))

print("predicted value by model: ",new_label)

Enter sepal_len(cm):6.2
Enter sepal_width(cm):3.4
Enter petal_len(cm):5.4
Enter petal_width(cm):2.3
predicted value by model:  ['Iris-virginica']
