In [41]:
import numpy as np
import pandas as pd
import random

data_set=pd.read_csv("C:\\Users\\HP\\Desktop\\Git_AI_Work\\AI & Machine Learning Algorithms\\Iris.csv")
data_set.head(150)

data_set=data_set.sample(frac=1)
# data_set.head(150)

In [42]:
features = data_set.values[:, 1:5]  #x
labels= data_set.values[: , 5]  # y

In [43]:
#75% training and 25% testing
test=0
train=input("enter training percentage: ")
# test=str(100-int(test))
#find 75% of 149 records


enter training percentage: 80


In [44]:
max_index=int(len(data_set)*int(train)/100)
# test1=len(data_set)-train1

feature_train=features[0:max_index,:]

feature_test=features[max_index:len(data_set),:]

label_train=labels[0:max_index]

label_test=labels[max_index:len(data_set)]

In [45]:
print(features)
print(labels)
print(feature_train)
print(feature_test)
print(label_train)
print(label_test)

[[5.0 3.6 1.4 0.2]
 [6.5 2.8 4.6 1.5]
 [6.1 2.8 4.7 1.2]
 [5.4 3.4 1.7 0.2]
 [6.7 3.1 5.6 2.4]
 [6.7 3.0 5.0 1.7]
 [7.6 3.0 6.6 2.1]
 [7.2 3.6 6.1 2.5]
 [6.4 2.8 5.6 2.1]
 [5.1 3.8 1.9 0.4]
 [6.4 3.2 5.3 2.3]
 [6.8 2.8 4.8 1.4]
 [5.4 3.0 4.5 1.5]
 [6.7 3.3 5.7 2.1]
 [5.2 3.5 1.5 0.2]
 [6.8 3.2 5.9 2.3]
 [7.7 3.8 6.7 2.2]
 [4.8 3.1 1.6 0.2]
 [7.3 2.9 6.3 1.8]
 [5.7 4.4 1.5 0.4]
 [5.0 3.4 1.6 0.4]
 [6.1 2.9 4.7 1.4]
 [5.7 2.6 3.5 1.0]
 [6.9 3.1 4.9 1.5]
 [6.1 2.6 5.6 1.4]
 [6.1 3.0 4.6 1.4]
 [6.8 3.0 5.5 2.1]
 [5.8 2.6 4.0 1.2]
 [5.1 3.8 1.6 0.2]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 4.1 1.0]
 [5.9 3.0 4.2 1.5]
 [4.6 3.2 1.4 0.2]
 [5.6 3.0 4.5 1.5]
 [5.6 2.8 4.9 2.0]
 [6.2 3.4 5.4 2.3]
 [4.9 3.1 1.5 0.1]
 [6.3 2.5 4.9 1.5]
 [6.5 3.2 5.1 2.0]
 [6.7 3.3 5.7 2.5]
 [5.5 2.6 4.4 1.2]
 [5.8 2.8 5.1 2.4]
 [5.0 3.5 1.3 0.3]
 [5.2 3.4 1.4 0.2]
 [6.0 2.2 4.0 1.0]
 [5.5 2.5 4.0 1.3]
 [7.9 3.8 6.4 2.0]
 [6.0 3.4 4.5 1.6]
 [6.4 2.7 5.3 1.9]
 [5.0 3.4 1.5 0.2]
 [5.1 3.5 1.4 0.3]
 [4.8 3.4 1.6 0.2]
 [5.6 2.9 3.

In [49]:
from sklearn.neural_network import MLPClassifier

# clf = MLPClassifier( alpha=1e-5,hidden_layer_sizes=(2,1), random_state=1)
clf = MLPClassifier( alpha=(1),hidden_layer_sizes=(1,1), random_state=1)

clf.fit(feature_train, label_train)
# MLPClassifier(alpha=1e-05, hidden_layer_sizes=(1, 3), random_state=1,solver='lbfgs')

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=1, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(1, 1), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=1, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [50]:
label_pred= clf.predict(feature_test)

In [51]:
count=0
for t,p in zip(label_test, label_pred):
    print(t+"->"+p)
    count=count+1
print("Total tsetings:",count)

count1=0
for t,p in zip(label_test, label_pred):
    if(t==p):
        count1=count1+1
    
print("correct pred:",count1)
acc=(count1/len(label_test))*100

print("Accuracy",acc)

Iris-versicolor->Iris-versicolor
Iris-setosa->Iris-versicolor
Iris-setosa->Iris-versicolor
Iris-setosa->Iris-versicolor
Iris-virginica->Iris-versicolor
Iris-setosa->Iris-versicolor
Iris-virginica->Iris-versicolor
Iris-setosa->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-virginica->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-virginica->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-virginica->Iris-versicolor
Iris-virginica->Iris-versicolor
Iris-virginica->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-virginica->Iris-versicolor
Iris-versicolor->Iris-versicolor
Iris-setosa->Iris-versicolor
Iris-setosa->Iris-versicolor
Iris-setosa->Iris-versicolor
Iris-virginica->Iris-versicolor
Iris-setosa->Iris-versicolor
Iris-virginica->Iris-versicolor
Iris-virginica->Iris-versicolor
Total tsetings: 30
correct pred: 10
Accuracy 33.333333333