In [3]:
import numpy as np
import os, os.path

dir ="."

onlyfiles = next(os.walk(dir))[2] #dir is your directory path as string
a = len(onlyfiles)

In [4]:
a

12

In [5]:
import numpy as np

In [6]:
x  = np.array([1,2,3])
print(x)

[1 2 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.dtype

dtype('int32')

In [13]:
y  = np.arange(1,10,2)
y

array([1, 3, 5, 7, 9])

In [14]:
y  = np.arange(0,15).reshape(5,3)

In [15]:
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
y.shape

(5, 3)

In [24]:
c  = np.zeros((5,3), dtype=np.int64)

In [25]:
c

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [23]:
c.dtype

dtype('float64')

# Pandas

In [26]:
import pandas as pd
import numpy as np
obj = pd.Series([4, 7, -5, 3])
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64


In [27]:
import pandas as pd
sales = pd.Series([100, 200, 100, 400])
print(sales.values)
print(sales.index)

[100 200 100 400]
RangeIndex(start=0, stop=4, step=1)


In [28]:
sales = pd.Series([100, 200, 100, 400], index = ['Jan', 'Feb', 'Mar','Apr'])
print(sales)
print(sales.values)
print(sales.index)

Jan    100
Feb    200
Mar    100
Apr    400
dtype: int64
[100 200 100 400]
Index(['Jan', 'Feb', 'Mar', 'Apr'], dtype='object')


In [29]:
monthNames  = ['Jan', 'Feb', 'Mar', 'Apr']
sales = pd.Series([100, 200, 100, 400], 
                  index = ['Jan', 'Feb', 'Mar','Apr'], 
                  name="4 month sales") 
# both are same
sales = pd.Series([100, 200, 100, 400], 
                  index = monthNames, 
                  name="4 month sales") 

print(sales)
print(sales.values)

Jan    100
Feb    200
Mar    100
Apr    400
Name: 4 month sales, dtype: int64
[100 200 100 400]


In [30]:
import calendar as cal
months = []

for i in range(1, 13):
    mnth = cal.month_abbr[i]
    months.append(mnth)
    
sw = pd.Series( np.random.randint(10,101 , size  = [12]) , 
               index = months)
print(sw)

Jan    88
Feb    73
Mar    98
Apr    51
May    89
Jun    86
Jul    83
Aug    20
Sep    79
Oct    20
Nov    30
Dec    87
dtype: int32


In [32]:
print(sw[1])
print(sw["Aug"])
print(sw["Dec"])


73
20
87


In [33]:
print(sw > 20)
print()
print(sw[sw > 20])


Jan     True
Feb     True
Mar     True
Apr     True
May     True
Jun     True
Jul     True
Aug    False
Sep     True
Oct    False
Nov     True
Dec     True
dtype: bool

Jan    88
Feb    73
Mar    98
Apr    51
May    89
Jun    86
Jul    83
Sep    79
Nov    30
Dec    87
dtype: int32
