In [2]:
import numpy as np

arr1=np.array([ [
                  [111, 112, 113] , 
                  [121, 122, 123] 
                ],
                [ 
                  [211, 212, 213] , 
                  [221, 222, 224] 
                ],
                [
                  [311, 312, 313], 
                  [321, 322, 323]
                ],
                [
                  [411, 412, 413],
                  [421, 422, 423] 
                ]
              ])

In [3]:
arr=np.zeros(10)
arr1=np.ones(10)

In [4]:
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
ndarr=np.array([
                [11,12,13,14],
                [21,22,23,24],
                [31,32,33,34],
                [41,42,43,44],

                ])

print(ndarr.shape)
print("N dimension array",ndarr)
print(ndarr[0:2])
print(ndarr[0:2, 3])
print(ndarr[0:2, 0])

(4, 4)
N dimension array [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
[[11 12 13 14]
 [21 22 23 24]]
[14 24]
[11 21]


In [6]:
ndarr=np.array([#1st dim
                    [#2nd dim
                         [111,112,113],#3rd dim
                         [121,122,123],
                         [131,132,133],
                         [141,142,143]
                    ],
                    [
                        [211,212,213],
                         [2221,222,223],
                         [231,232,233],
                         [241,242,243]
                    ],
                    [
                        [311,312,313],
                         [321,322,323],
                         [331,332,333],
                         [341,342,343]
                    ],
                    [
                        [411,412,413],
                         [421,422,423],
                         [431,432,433],
                         [441,442,443]
                    ]

                ])

print("Shape:",ndarr.shape)
#print("N dimension array",ndarr)
#print("\n\n")
#print("slicing\n",ndarr[0:4, 0:1])
#print("slicing\n",ndarr[0:4, 1:3])

# print("slicing\n",ndarr[0:4, 1:3, 1]) main he ye

# extras chal rha he

# print("slicing\n",ndarr[0:4, 1:3, 1]>200) or  =200
# print("slicing\n",ndarr[ndarr>200])#jha ye condition true hogi wo value print hojaegi
# print("slicing\n",ndarr200)#jha ye condition true hogi wo value pr true ajaega
na1=ndarr>200 #ndarr==212 ndarr<=12 ndarr
print(na1.shape)
na2=ndarr[na1]
print(na2.shape)
na3=na2.reshape([3,3,4])
print(na3)
# print("slicing\n",ndarr>200)

Shape: (4, 4, 3)
(4, 4, 3)
(36,)
[[[ 211  212  213 2221]
  [ 222  223  231  232]
  [ 233  241  242  243]]

 [[ 311  312  313  321]
  [ 322  323  331  332]
  [ 333  341  342  343]]

 [[ 411  412  413  421]
  [ 422  423  431  432]
  [ 433  441  442  443]]]


In [7]:
ndarr=np.array([#1st dim
                    [#2nd dim
                         [[1111,1112,1113],112,113],#3rd dim
                         [121,122,123],
                         [131,132,133],
                         [141,142,143]
                    ],
                    [
                        [211,212,213],
                         [2221,222,223],
                         [231,232,233],
                         [241,242,243]
                    ],
                    [
                        [311,312,313],
                         [321,322,323],
                         [331,332,333],
                         [341,342,343]
                    ],
                    [
                        [411,412,413],
                         [421,422,423],
                         [431,432,433],
                         [441,442,443]
                    ]

                ])

print("Shape:",ndarr.shape)
#print("N dimension array",ndarr)
#print("\n\n")
# print("slicing\n",ndarr[0:4, 0:1])
#print("slicing\n",ndarr[0:4, 1:3])

print("slicing\n",ndarr[0:4, 1:3, 1])

Shape: (4, 4, 3)
slicing
 [[122 132]
 [222 232]
 [322 332]
 [422 432]]


In [8]:
nd2=np.zeros([4,4,3,2,4],dtype="int16")

In [9]:
 print(nd2.shape)
# 
nd2[3,3,0,1,2]=123

print(nd2)
#js dimension ka slice nhi btate to us dimension ka pura data uth ka ajata he

(4, 4, 3, 2, 4)
[[[[[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]]


  [[[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]]


  [[[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]]


  [[[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]]]



 [[[[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]]


  [[[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]]


  [[[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]

   [[  0   0   0   0]
    [  0   0   0   0]]]


  

In [10]:
import numpy as np
mainArray=np.zeros([2,8])
subarray=np.ones(8)
print(mainArray.shape)
mainArray[0]=subarray
mainArray[1]=subarray*2
print(mainArray)

(2, 8)
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2.]]


In [14]:
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline

im = plt.imread("ahsan_pic.png")
print(im.shape)

mainArray=np.zeros([20,100,100,3])
print(mainArray.shape)
mainArray[2]=im[:100,:100,:3]
print(mainArray)

(747, 515, 4)
(20, 100, 100, 3)
[[[[0.         0.         0.        ]
   [0.         0.         0.        ]
   [0.         0.         0.        ]
   ...
   [0.         0.         0.        ]
   [0.         0.         0.        ]
   [0.         0.         0.        ]]

  [[0.         0.         0.        ]
   [0.         0.         0.        ]
   [0.         0.         0.        ]
   ...
   [0.         0.         0.        ]
   [0.         0.         0.        ]
   [0.         0.         0.        ]]

  [[0.         0.         0.        ]
   [0.         0.         0.        ]
   [0.         0.         0.        ]
   ...
   [0.         0.         0.        ]
   [0.         0.         0.        ]
   [0.         0.         0.        ]]

  ...

  [[0.         0.         0.        ]
   [0.         0.         0.        ]
   [0.         0.         0.        ]
   ...
   [0.         0.         0.        ]
   [0.         0.         0.        ]
   [0.         0.         0.        ]]

  [[0.       