In [1]:
import os
from PIL import Image
import numpy as np


# Set the directory you want to start from
rootDir = 'photos'
for dirName, subdirList, fileList in os.walk(rootDir):
    print('Found directory: %s' % dirName)
    for fname in fileList:
        print('\t%s' % fname)
    

Found directory: photos
	1.jpg
	10.jpg
	11.jpg
	12.jpg
	13.jpg
	14.jpg
	15.jpg
	16.jpg
	17.jpg
	18.jpg
	19.jpg
	2.jpg
	20.jpg
	3.jpg
	4.jpg
	5.jpg
	6.jpg
	7.jpg
	8.jpg
	9.jpg


In [2]:
main_list = []
im = Image.open(dirName+"\\"+fileList[0])
print("----------X------------X-----------------------X\n\n")
im.show()
original_array = np.array(im)
print(original_array.shape)
print(original_array.size)
print(original_array)
print("\n\n----------X------------X-----------------------X\n\n")
new_image = im.resize((200, 200))
resized_array = np.array(new_image)
print(resized_array.size)
print(resized_array.shape)
print(resized_array)
main_list.append(resized_array)

----------X------------X-----------------------X


(2160, 3840, 3)
24883200
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 ...

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 ...

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


In [3]:
main_list

[array([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        ...,
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=uint8)]

In [4]:
pic = 2
for i in range(1,len(fileList)):
    print("PIC NO : ",pic)
    im = Image.open(dirName+"\\"+fileList[i])           
    print("----------X------------X-----------------------X\n\n")
    im.show()
    original_array = np.array(im)
    print(original_array.shape)
    print(original_array.size)
    print(original_array)
    print("\n\n----------X------------X-----------------------X\n\n")
    new_image = im.resize((200, 200))
    resized_array = np.array(new_image)
    print(resized_array.size)
    print(resized_array.shape)
    print(resized_array)
    print("APPENDING TIME")
    main_list.append(resized_array)
    pic = pic+1

PIC NO :  2
----------X------------X-----------------------X


(2160, 3840, 3)
24883200
[[[151 151 151]
  [151 151 151]
  [210 210 210]
  ...
  [206 206 206]
  [178 178 178]
  [173 173 173]]

 [[158 158 158]
  [156 156 156]
  [211 211 211]
  ...
  [205 205 205]
  [181 181 181]
  [179 179 179]]

 [[209 209 209]
  [204 204 204]
  [255 255 255]
  ...
  [255 255 255]
  [238 238 238]
  [242 242 242]]

 ...

 [[197 197 197]
  [196 196 196]
  [254 254 254]
  ...
  [255 255 255]
  [226 226 226]
  [230 230 230]]

 [[173 173 173]
  [174 174 174]
  [232 232 232]
  ...
  [234 234 234]
  [198 198 198]
  [200 200 200]]

 [[173 173 173]
  [173 173 173]
  [232 232 232]
  ...
  [233 233 233]
  [193 193 193]
  [192 192 192]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[253 253 253]
  [253 253 253]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]



(1080, 1920, 3)
6220800
[[[238   0 140]
  [238   0 140]
  [238   0 140]
  ...
  [238   0 140]
  [238   0 140]
  [238   0 140]]

 [[238   0 140]
  [238   0 140]
  [238   0 140]
  ...
  [238   0 140]
  [238   0 140]
  [238   0 140]]

 [[238   0 140]
  [238   0 140]
  [238   0 140]
  ...
  [238   0 140]
  [238   0 140]
  [238   0 140]]

 ...

 [[225  77  89]
  [226  78  90]
  [226  78  90]
  ...
  [238   0 140]
  [238   0 140]
  [238   0 140]]

 [[226  78  90]
  [226  78  90]
  [226  78  92]
  ...
  [238   0 140]
  [238   0 140]
  [238   0 140]]

 [[226  78  92]
  [226  78  92]
  [226  78  92]
  ...
  [238   0 140]
  [238   0 140]
  [238   0 140]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[238   0 140]
  [238   0 140]
  [238   0 140]
  ...
  [238   0 140]
  [238   0 140]
  [238   0 140]]

 [[238   0 140]
  [238   0 140]
  [238   0 140]
  ...
  [238   0 140]
  [238   0 140]
  [238   0 140]]

 [[238   0 140]
  [238   0 140]
  [238   0 140]
  ...
  [238   0

(2160, 3840, 3)
24883200
[[[ 36  22   0]
  [ 80  61  18]
  [139 110  44]
  ...
  [205 168  51]
  [202 165  48]
  [201 164  47]]

 [[ 39  25   0]
  [ 87  68  25]
  [137 108  42]
  ...
  [203 166  49]
  [198 161  44]
  [201 164  47]]

 [[ 35  21   0]
  [ 80  61  18]
  [137 108  42]
  ...
  [205 168  51]
  [200 163  46]
  [200 163  46]]

 ...

 [[ 26   6   0]
  [ 61  38   7]
  [ 99  69  15]
  ...
  [ 88  42   8]
  [ 93  49  12]
  [ 96  52  15]]

 [[ 30  10   3]
  [ 58  34   8]
  [ 93  63  13]
  ...
  [ 89  43  10]
  [ 92  48  13]
  [ 91  47  10]]

 [[ 29  10   4]
  [ 60  38  14]
  [ 97  69  22]
  ...
  [ 94  48  15]
  [ 96  52  17]
  [ 95  51  14]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[175 129  35]
  [161 116  23]
  [174 128  34]
  ...
  [203 167  47]
  [200 164  44]
  [206 169  52]]

 [[180 134  40]
  [171 126  33]
  [179 132  40]
  ...
  [202 167  49]
  [203 167  47]
  [206 170  50]]

 [[174 127  35]
  [175 130  37]
  [177 130  38]
  ...
  [204 16

In [5]:
len(main_list)

20

In [6]:
main_list

[array([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        ...,
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=uint8), array([[[253, 253, 253],
         [253, 253, 253],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
       

In [7]:
main_arr= np.array(main_list)
print("FINAL NUMPY ARRAY :\n\n ",main_arr)

FINAL NUMPY ARRAY :

  [[[[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  ...

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]]


 [[[253 253 253]
   [253 253 253]
   [254 254 254]
   ...
   [254 254 254]
   [254 254 254]
   [254 254 254]]

  [[254 254 254]
   [254 254 254]
   [254 254 254]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[254 254 254]
   [254 254 254]
   [254 254 254]
   ...
   [255 255 255]
   [2

In [8]:
main_arr.shape

(20, 200, 200, 3)

In [9]:
main_arr.ndim

4

In [10]:
main_arr.size

2400000