In [2]:
#lets work with people height and weight 
import numpy as np

height= np.round(np.random.normal(1.75,0.20,5000),2)
weight= np.round(np.random.normal(60.32,0.15,5000),2)

In [3]:
print(height)

[1.61 1.32 1.49 ... 1.98 1.89 1.95]


In [5]:
city = np.column_stack((height,weight))

In [6]:
print(city)

[[ 1.61 60.34]
 [ 1.32 60.42]
 [ 1.49 60.17]
 ...
 [ 1.98 60.38]
 [ 1.89 60.25]
 [ 1.95 60.45]]


In [7]:
np.mean(city[:,0])

1.752154

In [8]:
np.median(city[:,0])

1.75

In [9]:
np.std(city[:,0])

0.20089285772271745

In [10]:
np.corrcoef(city[:,0],city[:,1])

array([[1.        , 0.00281287],
       [0.00281287, 1.        ]])